sparkjob:
  image:
    repository: spark
    tag: "3.5.0-scala2.12-java11-python3-ubuntu"
    pullPolicy: IfNotPresent

  job:
    type: Python
    sparkVersion: "3.5.0"
    mainApplicationFile: "local:///app/main.py"
    arguments: []

  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "1g"
    env: []

  executor:
    instances: 2
    cores: 2
    memory: "2g"

  sparkConf:
    spark.sql.adaptive.enabled: "true"
    spark.sql.shuffle.partitions: "10"

  restartPolicy:
    type: OnFailure
    onFailureRetries: 3
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 5
    onSubmissionFailureRetryInterval: 20

  serviceAccount:
    create: true
